### ISSUE TITLE
cant send coins

### ISSUE THREAD

**Issue by saymissme** [haven-protocol-org/haven-protocol#4]
wallet log is here

daemon got this info:
> 2020-05-26 10:37:18.044 [RPC1]  WARNING daemon.rpc      src/rpc/core_rpc_server.cpp:770 [on_send_raw_tx]: tx verification failed: bad ring size, invalid input

can you help me?
thx

**Comment by dweab** [comment]
It looks like you're trying to use a ring size of 20. We only support a ring size of 11. You will probably need to close your wallet, delete ./shared-ringdb and then restart your wallet to clear these failed txs.

**Comment by dweab** [comment]
Ah - I see you run pool software. Can you join our discord to talk more please - pool configs are sometimes more complex to correct.

**Comment by saymissme** [comment]
i was fixed it
thankyou very much
